### ISSUE TITLE
cannot pip install tabel on python 3.6 without LC_ALL=C.UTF-8

### ISSUE THREAD

**Issue by mdaniel** [BastiaanBergman/tabel#6]
Due to the presence of the unicode characters in the description, if the `LC_ALL` environment variable isn't just right, python will attempt to read the description as ascii, resulting in a `UnicodeDecodeError`
 
```console
$ docker run --rm -it -e LC_ALL=C python:3.6 bash -c 'pip install tabel==1.2.0'
Collecting tabel==1.2.0
  Downloading https://files.pythonhosted.org/packages/c1/85/d7c4a7100f3bd0a3d603f564d93d2436e33fbb9e8c1b0c276c8535b326c1/tabel-1.2.0.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-s5oh0_uq/tabel/setup.py", line 6, in <module>
        long_description = fh.read()
      File "/usr/local/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xcb in position 7718: ordinal not in range(128)
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-s5oh0_uq/tabel/
```

One can see that the unicode characters are only present in the IPA string, and thus can either be omitted or HTML encoded and this problem will go away:

```console
$ tar -xOzf tabel-1.2.0.tar.gz 'tabel-1.2.0/PKG-INFO' | grep Dutch | od -c
0000000                                   *   T   a   b   e   l   *    
0000020   /   t   a 313 220 313 210   b 311 233   l   /       i   s    
```

**Comment by BastiaanBergman** [comment]
Thanks for noting! The unicode should be all removed now in version 1.2.1.
